### ISSUE TITLE
Can we disable `S3 Deploy` workflow under Actions?

### ISSUE THREAD

**Issue by sidetrackedmind** [codeforpdx/opentransit-metrics#22]
## issue
This workflow has been failing with every commit - https://github.com/codeforpdx/opentransit-metrics/blob/master/.github/workflows/deploy.yml. Can we disable it? Maybe create another issue for fixing it?

**Comment by sidetrackedmind** [comment]
only run this workflow - if secrets are configured `secrets.AWS_ACCESS_KEY_ID` do not run if not

**Comment by liamphmurphy** [comment]
Been doing a lot at work on migrating our Jenkins CI to GH Actions, so this caught my eye. 

As for fixing the issue; I don't have admin access to the repo. Do those secrets exist in the Settings? It could be they disappeared when we forked...?

**Comment by sidetrackedmind** [comment]
I'm closing this issue because @liamphmurphy took care of it under PR #27.
